; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3camlcd]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi ; Critical for 8MB PSRAM on S3-CAM
board_build.flash_mode = qio
board_build.psram_type = opi

build_flags =
    -Os
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    mathieucarbou/ESPAsyncWebServer @ ^3.3.12
    esp32-camera
